### PR TITLE
Tabs, Styling, Variable declarations... Minor things

### PR DESCRIPTION
**Pull request by lukeed**
I'd understand if you rejected based on the style changes alone :) 

Removed unnecessary variable declarations.
Updated to tabs.
Simplified a repetitive switch loop.

Overall, shaved 3ms (average) in the test suite.

### CODE REVIEW

**Comment by lukeed** [comment]
Actually, is 10-12ms faster based on Travis' build history :wink:

**Comment by PabloVallejo** [comment]
hi @lukeed,

Thanks a lot for this revision :wink:

The project was originally created using [jQuery's coding style](https://github.com/jquery/jquery/blob/master/src/core/access.js#L7) and also [laxcomma](http://jshint.com/docs/options/#laxcomma) so that I thinks we should keep using them.

I had specified `indent_style = tab` in `.editorconfig` however the main file was using spaces. Nevertheless I think we're better off with spaces given that they're the same across different environments.

On the other hand It's hard to see which lines are changed in the diff given the tabs. So, can you make smaller PR's so that we can go little by little through each one. We can start by a PR with this commit ca17ba1b77d7d6592747e31da1ac4014cdb356f1

Thanks again :+1: !

**Comment by lukeed** [comment]
Hey Pablo,

No problem!

Tabs are also the same across all environments, just provide extra capability to show as 2 or 4, as preference.

It's only hard to compare in this PR because all lines changed. 

And amidst all the tabs, I think only 6 var declarations were removed. 

So, frankly, I don't think it's worth the time to go back and re-commit things just for the sake of the log. And especially, personally, I can't stand that styling lol. 

I won't be offended if you reject this. I mostly was going through with a comb for myself in order to understand what was going on and decide if it was something that suited a minor project. 

Best & thanks!

**Comment by PabloVallejo** [comment]
@lukeed definitely the coding style you're using is the one most commonly used in JavaScript. 

At the time I wrote the first version I was heavily inspired by the jQuery library and Twitter Bootstrap plugins so I took the coding style from both, nevertheless I don't have a particular preference for it, so I'm totally fine with the [Airbnb like coding style](https://github.com/airbnb/javascript).

Having said so I'm going to merge this PR and release a new version.

Thanks!

**Comment by lukeed** [comment]
Yup, no worries! Time definitely allows things/styles to change and emerge. Nothing wrong with the "old" way. :+1:

**Comment by PabloVallejo** [comment]
On the other hand, I going to use spaces as the standard.
There's no really a compelling reason for this but personal preference, you can use tabs locally and then commit with spaces.

There are multiple discussions about what's better but I think that ultimately no one has that many advantages over the other, so I think it's a matter of picking one.

**Pull request merged**
